# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 06:11
from __future__ import unicode_literals

from django.db import migrations
import djgeojson.fields


class Migration(migrations.Migration):

    dependencies = [
        ('carwash', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carwash',
            name='GeoPoint',
            field=djgeojson.fields.PointField(default=1),
            preserve_default=False,
        ),
    ]
