# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 06:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carwash', '0002_carwash_geopoint'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carwash',
            old_name='GeoPoint',
            new_name='geopoint',
        ),
    ]
