# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 06:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carwash', '0003_auto_20160420_0626'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carwash',
            old_name='geopoint',
            new_name='geom',
        ),
    ]
