# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carwash', '0005_carwash_fk_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='carwash',
            name='workload',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
